### ISSUE TITLE
Add XLIFF linting to ddev

### ISSUE THREAD

**Issue by ayacoo** [FriendsOfTYPO3/tea#297]
Hi, i followed Oli's testing session with interest and ended up here.

We currently still have a linter in our pipelines that checks the XLiff files. This shows me the errors, as a lot is happening in the copy/paste game ;-) The basis for this is XLIFF version 1.2.

I don't know if this is easy in the context of the extension, but here is the code of the gitlab job

```
xlifflint:
  image: php:7.4
  stage: quality
  before_script:
    - apt-get update && apt-get install -y wget libxml2-utils
  script:
    - wget https://raw.githubusercontent.com/symfony/translation/v4.1.1/Resources/schemas/xliff-core-1.2-strict.xsd
    - xmllint --schema xliff-core-1.2-strict.xsd --noout $(find packages/ext-path/Resources/Private/Language -name '*.xlf')
  allow_failure: false
```

You could also build it into the composer script section, but as a basis you would need a package installation on the part of ddev or the system. I don't know if this is in the sense of the extension and documentation.
